### ISSUE TITLE
Crash after automatical update!

### ISSUE THREAD

**Issue by jules103** [MSourceCoded/SourceCodedCore#4]
think you just crashed every modsauce server in the world! i had to manually roll back to the older 100b version

**Comment by jules103** [comment]
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.io.IOException: Destination '/srv/minecraft/config/sourcecodedcore.cfg/../../configOld' directory cannot be created
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:515)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:319)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:170)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Destination '/srv/minecraft/config/sourcecodedcore.cfg/../../configOld' directory cannot be created
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1085)
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1038)
	at org.apache.commons.io.FileUtils.moveFile(FileUtils.java:2832)
	at sourcecoded.core.configuration.VersionConfig.setupVersioning(VersionConfig.java:54)
	at sourcecoded.core.configuration.VersionConfig.createNewVersionConfig(VersionConfig.java:37)
	at sourcecoded.core.SourceCodedCore.preInit(SourceCodedCore.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
	... 5 more

**Comment by chrisk123999** [comment]
Getting this error as well.  Even turning off the version checking still results in this issue.

**Comment by MSourceCoded** [comment]
If you're running Linux make sure you have write permissions to the directory 2 levels up from /config/
The reason is that your configuration is out of date. Try changing the 'version' property in the config to 0.4 and then relaunch for a temp fix. I will look more into it.

**Comment by chrisk123999** [comment]
I do have permission that far up, but it's still running into that issue.  I don't think it's going back directories correctly on Linux.

**Comment by chrisk123999** [comment]
"/srv/minecraft/config/sourcecodedcore.cfg/../../configOld"
Seems it's trying to go to a folder that includes the file name of the config file.
